import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { SlidersHorizontal, X } from "lucide-react";
import HostelCard from "../components/HostelCard";
import FilterPanel, { Filters } from "../components/FilterPanel";
import EmptyState from "../components/EmptyState";
import { HostelGridSkeleton } from "../components/LoadingSkeleton";
import Button from "../components/Button";
import { hostels } from "../data/hostels";
import { useSavedHostels } from "../hooks/useSavedHostels";
const SORT_OPTIONS = [{ label: "Recommended", value: "recommended" }, { label: "Price: Low to High", value: "price-asc" }, { label: "Price: High to Low", value: "price-desc" }, { label: "Distance", value: "distance" }];
const DEFAULT_FILTERS: Filters = { maxPrice: 10000, maxDistance: 3, roomType: "Any", facilities: [], gender: "Any" };
const ROOM_TYPE_MAP: Record<string, string> = { single: "Single Room", double: "Two Sharing", quad: "Four Sharing" };
export default function Hostels() {
  const [searchParams] = useSearchParams(); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(searchParams.get("q") ?? ""); const [sort, setSort] = useState("recommended"); const [mobileFiltersOpen, setMobileFiltersOpen] = useState(false);
  const [filters, setFilters] = useState<Filters>(() => { const priceParam = searchParams.get("price"); const roomParam = searchParams.get("room"); return { ...DEFAULT_FILTERS, maxPrice: priceParam ? Number(priceParam.split("-")[1]) : DEFAULT_FILTERS.maxPrice, roomType: roomParam ? ROOM_TYPE_MAP[roomParam] ?? "Any" : "Any" }; });
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 500); return () => clearTimeout(timer); }, []);
  const { isSaved, toggleSaved } = useSavedHostels();
  const filtered = useMemo(() => { let result = hostels.filter((h) => { const matchesQuery = !query || h.name.toLowerCase().includes(query.toLowerCase()) || h.location.toLowerCase().includes(query.toLowerCase()); const matchesPrice = h.price <= filters.maxPrice; const matchesDistance = h.distanceKm <= filters.maxDistance; const matchesRoom = filters.roomType === "Any" || h.roomTypes.some((r) => r.name === filters.roomType); const matchesGender = filters.gender === "Any" || h.genderPreference === filters.gender || h.genderPreference === "Mixed"; const matchesFacilities = filters.facilities.every((f) => h.facilities.includes(f)); return matchesQuery && matchesPrice && matchesDistance && matchesRoom && matchesGender && matchesFacilities; }); switch (sort) { case "price-asc": result = [...result].sort((a,b)=>a.price-b.price); break; case "price-desc": result = [...result].sort((a,b)=>b.price-a.price); break; case "distance": result = [...result].sort((a,b)=>a.distanceKm-b.distanceKm); break; } return result; }, [query, filters, sort]);
  const clearFilters = () => { setFilters(DEFAULT_FILTERS); setQuery(""); };
  return (<div className="bg-bg"><div className="border-b border-slate-200 bg-white"><div className="container-page py-10"><h1 className="text-2xl font-bold tracking-tight text-brand-navy sm:text-3xl">Find your next home at MMUST</h1><p className="mt-1.5 text-subink">Browse accommodation options located within the MMUST school compound.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><input type="text" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search by hostel name or location" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:border-brand-blue focus:outline-none focus:ring-1 focus:ring-brand-blue"/><button type="button" onClick={()=>setMobileFiltersOpen(true)} className="flex shrink-0 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-ink lg:hidden"><SlidersHorizontal size={16}/>Filters</button></div></div></div><div className="container-page grid grid-cols-1 gap-8 py-10 lg:grid-cols-[280px_1fr]"><aside className="hidden lg:block"><div className="sticky top-24"><FilterPanel filters={filters} onChange={setFilters} onClear={clearFilters}/></div></aside><div><div className="mb-5 flex items-center justify-between"><p className="text-sm text-subink"><span className="font-semibold text-ink">{loading ? "…" : filtered.length}</span> hostels found</p><select value={sort} onChange={(e)=>setSort(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-brand-blue focus:outline-none">{SORT_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>{loading ? <HostelGridSkeleton/> : filtered.length===0 ? <EmptyState title="No hostels match your current filters." description="Try widening your price range or clearing a few filters to see more options." action={<Button onClick={clearFilters}>Clear Filters</Button>}/> : <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(h=><HostelCard key={h.id} hostel={h} isSaved={isSaved(h.id)} onToggleSave={toggleSaved}/>)}</div>}</div></div>{mobileFiltersOpen && <div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-brand-navy/50" onClick={()=>setMobileFiltersOpen(false)}/><div className="absolute inset-y-0 right-0 w-full max-w-sm overflow-y-auto bg-bg p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-ink">Filters</h2><button type="button" aria-label="Close filters" onClick={()=>setMobileFiltersOpen(false)} className="rounded-full p-1.5 hover:bg-slate-100"><X size={18}/></button></div><FilterPanel filters={filters} onChange={setFilters} onClear={clearFilters}/><Button fullWidth className="mt-4" onClick={()=>setMobileFiltersOpen(false)}>Show {filtered.length} hostels</Button></div></div>}</div>);
}
