import { useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { Heart, MapPin, Users } from "lucide-react";
import { getHostelById } from "../data/hostels";
import { useSavedHostels } from "../hooks/useSavedHostels";
import ImageGallery from "../components/ImageGallery";
import FacilityList from "../components/FacilityList";
import RoomCard from "../components/RoomCard";
import Button from "../components/Button";
export default function HostelDetails() {
  const { id } = useParams<{id:string}>(); const navigate=useNavigate(); const hostel=id?getHostelById(id):undefined; const {isSaved,toggleSaved}=useSavedHostels(); const [selectedRoomId,setSelectedRoomId]=useState<string|null>(null);
  if(!hostel) return <Navigate to="/hostels" replace/>;
  const selectedRoom=hostel.roomTypes.find(r=>r.id===selectedRoomId)??hostel.roomTypes[0];
  const handleBookNow=()=>{const roomId=selectedRoomId??hostel.roomTypes.find(r=>r.available)?.id;if(!roomId)return;navigate(`/booking?hostel=${hostel.id}&room=${roomId}`)};
  return <div className="container-page py-8"><nav className="mb-5 text-sm text-subink"><Link to="/hostels" className="hover:text-brand-blue">Hostels</Link><span className="mx-1.5">/</span><span className="text-ink">{hostel.name}</span></nav><ImageGallery images={hostel.images} alt={hostel.name}/><div className="mt-8 grid grid-cols-1 gap-10 lg:grid-cols-[1fr_360px]"><div><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-brand-navy sm:text-3xl">{hostel.name}</h1><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-subink"><span className="flex items-center gap-1"><MapPin size={14}/> Within MMUST school compound</span><span className="flex items-center gap-1"><Users size={14}/> {hostel.genderPreference}</span></div></div><button type="button" aria-label={isSaved(hostel.id)?"Remove from saved hostels":"Save this hostel"} onClick={()=>toggleSaved(hostel.id)} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-slate-200 hover:border-brand-blue"><Heart size={18} className={isSaved(hostel.id)?"fill-brand-blue text-brand-blue":"text-slate-500"}/></button></div><section className="mt-8"><h2 className="font-semibold text-ink">About this hostel</h2><p className="mt-2 leading-relaxed text-subink">{hostel.description}</p></section><section className="mt-8"><h2 className="font-semibold text-ink">Facilities</h2><div className="mt-3"><FacilityList facilities={hostel.facilities} variant="grid"/></div></section><section className="mt-8"><h2 className="font-semibold text-ink">Room options</h2><div className="mt-3 grid grid-cols-1 gap-4 sm:grid-cols-2">{hostel.roomTypes.map(room=><RoomCard key={room.id} room={room} selected={selectedRoomId?selectedRoomId===room.id:room.id===hostel.roomTypes[0].id} onSelect={setSelectedRoomId}/>)}</div></section></div><aside><div className="sticky top-24 rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs text-subink">From</p><p className="text-2xl font-bold text-brand-navy">KSh {selectedRoom.price.toLocaleString()}<span className="text-sm font-medium text-subink">/semester</span></p><p className="mt-1 text-sm text-subink">{selectedRoom.name}</p><Button fullWidth size="lg" className="mt-5" onClick={handleBookNow}>Book Now</Button><p className="mt-3 text-center text-xs text-subink">You won't be charged yet — this submits a booking request.</p></div></aside></div></div>;
}
